training:
  batch_size: 16
  n_epochs: 200000
  n_iters: 50000001

data:
  dataset: "FashionMNIST"
  image_size: 28
  channels: 1
  logit_transform: false

model:
  mid_dim: 1024
  n_steps: 100
  schedule: 'linear'
  sigma_begin: 0.00001
  sigma_end: 0.01
  num_classes: 10

optimizer:
  weight_decay: 0.000
  optimizer: 'Adam'
  lr: 0.001
  beta1: 0.9